"""
events.py — Geopolitical events endpoints
"""
from fastapi import APIRouter, Depends, HTTPException, Query
from pydantic import BaseModel
from typing import Optional, List
from datetime import date
from app.core.security import check_rate_limit, TokenData
from app.core.database import get_neo4j_session, get_redis
import json

router = APIRouter()


class EventOut(BaseModel):
    event_id: str
    title: str
    event_type: str
    severity: float
    summary: Optional[str] = None
    source_url: Optional[str] = None
    date: str
    affected_sectors: List[str] = []
    countries_involved: List[str] = []


@router.get("/", response_model=List[EventOut])
async def list_events(
    event_type: Optional[str] = Query(None),
    min_severity: float = Query(0.0, ge=0.0, le=1.0),
    country: Optional[str] = Query(None, description="ISO3 code"),
    from_date: Optional[date] = Query(None),
    to_date: Optional[date] = Query(None),
    limit: int = Query(50, le=200),
    neo4j=Depends(get_neo4j_session),
    _: TokenData = Depends(check_rate_limit),
):
    """List geopolitical events with filters."""
    conditions = ["e.severity >= $min_severity"]
    params = {"min_severity": min_severity, "limit": limit}

    if event_type:
        conditions.append("e.event_type = $event_type")
        params["event_type"] = event_type.upper()
    if from_date:
        conditions.append("e.date >= date($from_date)")
        params["from_date"] = str(from_date)
    if to_date:
        conditions.append("e.date <= date($to_date)")
        params["to_date"] = str(to_date)

    where_clause = " AND ".join(conditions)

    if country:
        query = f"""
        MATCH (c:Country {{iso3: $country}})-[:INVOLVED_IN]->(e:Event)
        WHERE {where_clause}
        OPTIONAL MATCH (other:Country)-[:INVOLVED_IN]->(e)
        RETURN e.event_id AS event_id, e.title AS title, e.event_type AS event_type,
               e.severity AS severity, e.summary AS summary, e.source_url AS source_url,
               toString(e.date) AS date, e.affected_sectors AS affected_sectors,
               collect(DISTINCT other.iso3) AS countries_involved
        ORDER BY e.date DESC, e.severity DESC
        LIMIT $limit
        """
        params["country"] = country.upper()
    else:
        query = f"""
        MATCH (e:Event)
        WHERE {where_clause}
        OPTIONAL MATCH (c:Country)-[:INVOLVED_IN]->(e)
        RETURN e.event_id AS event_id, e.title AS title, e.event_type AS event_type,
               e.severity AS severity, e.summary AS summary, e.source_url AS source_url,
               toString(e.date) AS date, e.affected_sectors AS affected_sectors,
               collect(DISTINCT c.iso3) AS countries_involved
        ORDER BY e.date DESC, e.severity DESC
        LIMIT $limit
        """

    result = await neo4j.run(query, params)
    records = await result.data()
    return records


@router.get("/{event_id}", response_model=EventOut)
async def get_event(
    event_id: str,
    neo4j=Depends(get_neo4j_session),
    _: TokenData = Depends(check_rate_limit),
):
    """Get a single event by ID."""
    query = """
    MATCH (e:Event {event_id: $event_id})
    OPTIONAL MATCH (c:Country)-[:INVOLVED_IN]->(e)
    RETURN e.event_id AS event_id, e.title AS title, e.event_type AS event_type,
           e.severity AS severity, e.summary AS summary, e.source_url AS source_url,
           toString(e.date) AS date, e.affected_sectors AS affected_sectors,
           collect(DISTINCT c.iso3) AS countries_involved
    """
    result = await neo4j.run(query, event_id=event_id)
    records = await result.data()
    if not records:
        raise HTTPException(404, f"Event '{event_id}' not found")
    return records[0]


@router.get("/today/digest")
async def todays_digest(
    _: TokenData = Depends(check_rate_limit),
):
    """Get cached daily digest (generated by the reporter agent each morning)."""
    redis = get_redis()
    from datetime import datetime
    cache_key = f"digest:{datetime.utcnow().strftime('%Y-%m-%d')}"
    cached = await redis.get(cache_key)
    if not cached:
        raise HTTPException(404, "Today's digest not yet generated. Check back later.")
    return json.loads(cached)


@router.get("/trending/now")
async def trending_events(
    hours: int = Query(24, le=168),
    limit: int = Query(10, le=50),
    neo4j=Depends(get_neo4j_session),
    _: TokenData = Depends(check_rate_limit),
):
    """Get the most severe events in the recent time window."""
    query = """
    MATCH (e:Event)
    WHERE e.date >= date() - duration({hours: $hours})
    OPTIONAL MATCH (c:Country)-[:INVOLVED_IN]->(e)
    RETURN e.event_id AS event_id, e.title AS title, e.event_type AS event_type,
           e.severity AS severity, e.summary AS summary,
           toString(e.date) AS date,
           collect(DISTINCT c.iso3) AS countries_involved
    ORDER BY e.severity DESC
    LIMIT $limit
    """
    result = await neo4j.run(query, hours=hours, limit=limit)
    return await result.data()
